### PR TITLE
Added an option to use stdin and stdout

### PR DESCRIPTION
**Pull request by psavery**
If, in the place of the input file argument the user says
"--use_stdin_stdout", then the program will use stdin to read
the input, and it will print all output to stdout. This is great for
programs running bind as a subprocess. Also, one line is printed to
the end of the band data to indicate a completion of the band data.

### CODE REVIEW

**Comment by psavery** [comment]
I'm not sure yet what kind of an effect this might have when using a mac because I see that it opens a file dialog for macs, but this is pretty cool to use on linux!

If you run ./bind --use_stdin_stdout, since it reads from stdin, you can literally type the whole file in one line at a time (or copy and paste it), and then press ctrl-D to send EOF and then it runs it. I think that's pretty neat! It then prints out everything (status file, FMO file, band file, out file, etc.) to stdout.

**Comment by greglandrum** [comment]
I'm not around this weekend, but I'll try it on a modern Mac early next week.

**Comment by psavery** [comment]
Okay. I got to try it out on a friend's Mac just a little bit earlier. If we use the Fortran compilers (i. e. -DUSE_F2C=OFF in the cmake definitions), the program seems to run just fine. For that reason, we may not need to define those definitions for Mac computers (the -DUSING_THE_MAC), for everything seems to compile just as linux does.

The one issue I ran into, though, is the f2c library. Hopefully we can find one that works. The one I tried is this one: https://hamishrickerby.com/2009/02/20/installing-f2c-on-a-mac/#disqus_thread

That downloads, compiles, and installs (with root privileges) an f2c library. Before, the mac was complaining that it couldn't find f2c.h and it couldn't link to libf2c.a. This fixed it - it had both of them. However, it always crashed when it ran functions from the f2c files. So, there must be something wrong with the library (or perhaps we have to do a different f2c conversion on mac than we do on linux). I'm not sure. Then again, I think that that libf2c.a was compiled using appleclang, and the f2c files in yaehmop want to link to functions compiled with gnu gcc. That's probably the issue.

I can't test it much because I don't own a mac myself. I might ask Geoff or someone else who uses Macs to look into it... But if we can get the f2c to work on Macs, then everything should work on them as well.

I've been able to do some stuff with this in Avogadro. It's looking really cool!

**Comment by psavery** [comment]
Oh yes, and I updated this pull request to remove the merge conflicts.

**Comment by greglandrum** [comment]
I will take a more detailed look when I am back in Basel on Monday

**Comment by psavery** [comment]
I need to confirm this with Marcus, but it sounds like we may just precompile yaehmop separately and have developers download the binaries instead of compiling it themselves. I think this would be a big plus because we won't have to worry about this f2c stuff - we can use the fortran compilers. In addition, we would be able to link to the blas and lapack libraries as well - so hopefully it would be faster for the user. I'll let you know when I get confirmation about that.

**Comment by psavery** [comment]
Indeed, I confirmed with Marcus. It sounds like, for now, we will just compile the yaehmop executables for the different operating systems separately (and installing them when we install avogadro). This means we don't necessarily need to get F2C working on the mac right now (although Marcus mentioned it would be nice....). So yeah. Just thought I'd update you about that.

**Pull request merged**
