### PR TITLE
Allow calling the eHT code as a library

### PR DESCRIPTION
**Pull request by greglandrum**
The idea here is to allow the eHT code to be called as a library from other software.
A reasonable amount of cleanup work was required, but at this point doing molecular calculations works cleanly. I've tested the molecular code with valgrind and confirmed that it's safe to call `run_eht()` (the new driver function) multiple times from other software.

### CODE REVIEW

**Comment by greglandrum** [comment]
@psavery it would be great if you had time/interest to take a look at this. I think it could also be helpful for avogadro since it opens up the possibility to skip calling a separate executable.
After merging we'd need to ensure that doing extended calculations works this way too (I haven't tested that at all).
Note: this now builds without problems under windows using Visual Studio.

**Comment by psavery** [comment]
@greglandrum I think it looks pretty cool!

I think it'd be nice to be able to link to yaehmop and call it directly instead of making external executables. Because of this PR and PR #20, we would hopefully be able to build it and link to it more easily on Windows, Mac, and Linux, right?

I know it'd probably be a little slower without BLAS and LAPACK, but we can find ways to make that optional during the build with Avogadro as well.

**Comment by richardjgowers** [comment]
@greglandrum do you need this testing on Mac? I could try and put the changes I did in #24 onto this branch?

**Comment by greglandrum** [comment]
@psavery: I think this should make it easier to build cross platform.
Certainly windows and Linux now work and I assume the Mac will be easy (don’t have mine with me to confirm that).
We should consider adding support for Eigen as an alternative to Lapack that’s easier to install. Maybe for a future PR.

**Comment by greglandrum** [comment]
@richardjgowers: would be awesome if you could test on the Mac; I don’t have mine with me at the moment.

Don’t worry about your PR, I should be able to merge it without problems

**Comment by richardjgowers** [comment]
@greglandrum I did a `cmake .`, `make` and got something about `bzero` being declared twice:

```
In file included from /Users/richardgowers/code/yaehmop/tightbind/test_driver.c:33:
/Users/richardgowers/code/yaehmop/tightbind/bind.h:266:9: warning: 'bzero' macro redefined [-Wmacro-redefined]
#define bzero(a, b) (memset((void *)(a), 0, (b)))
        ^
/usr/include/secure/_strings.h:52:9: note: previous definition is here
#define bzero(dest, ...)
```

If I comment out the definiton in `bind.h` I get this instead:

```
Undefined symbols for architecture x86_64:
  "_zheev_", referenced from:
      _construct_band_structure in libyaehmop_eht.a(bands.c.o)
      _loop_over_k_points in libyaehmop_eht.a(kpoints.c.o)
  "_zhegv_", referenced from:
      _diagonalize_FMO in libyaehmop_eht.a(FMO_stuff.c.o)
      _construct_band_structure in libyaehmop_eht.a(bands.c.o)
      _loop_over_k_points in libyaehmop_eht.a(kpoints.c.o)
```

Which isn't immediately obvious to fix?

**Comment by greglandrum** [comment]
@richardjgowers I just checked something in that fixes the bzero warning.

The errors about zheev and zhegv are probably showing up because it's trying to link against blas and lapack. You can disable this by passing `-DUSE_BLAS_LAPACK=OFF` to cmake.

As a general thing; I don't think either of those should be connected to the changes I made on this branch.

**Comment by greglandrum** [comment]
Ok, it's now merged... let's see what kind of cool stuff we can do now that you can use the eHT code as a library. :-)

**Comment by greglandrum** [comment]
@psavery : I've been doing the development work here on Windows and the Linux and using cmake + the native compiler works fine with both of them.

**Comment by ghutchis** [comment]
@greglandrum - when I get a chance (which may be February at this rate) I’ll look at this for Avogadro2. I’d really love to have a “show me the orbitals” command for whatever the user has on screen.

**Comment by greglandrum** [comment]
@ghutchis: let me know when you’re there; that would be pretty cool

**Comment by psavery** [comment]
@ghutchis I'm working on submitting a PR to Avogadro2 that builds and includes yaehmop. I submitted PR #25 here to help with that...

**Pull request merged**
